title: Blog of Shuo
author: irving-11
email: 1827108135@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Jack Shuo
  tagline: Student. Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  #favicon: /favicon.ico
  # generate social links in footer
  social_links:
    twitter: lishuo55153960
    github:  irving-11
    linkedIn: in/none
    instagram: none 
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

#gitalk
gitalk:
    owner: irving-11
    repo: blogtalk
    clientID: 6afa26e231d65fb24b3d
    clientSecret: 62ce78feab2e160348b92d5defad3f33ea955bcf
# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
